  version: "3"
  services:
    springbootapp:
      build: .
      container_name: springbootapp
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_nura
      ports:
        - 8000:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=nura
        - POSTGRES_PASSWORD=nura
        - POSTGRES_DB=db_nura
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5000:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
  volumes:
    pgdata: